INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Adam','First man created by the Lord God in His image. Brought sin into the world upon mankind through his disobedience. Husband of Eve. Father of Cain, Abel, Seth, others unnamed.',0,930,NULL,NULL,NULL),
	 ('Eve','Created by God from the side rib of Adam. Wife of Adam. Deceived by Satan into eating the fruit of the tree of the knowledge of good and evil.',NULL,NULL,NULL,NULL,'wife'::public.spouse_relationship),
	 ('Cain','Firstborn of Adam. Murdered his brother Abel.',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Abel','Second son of Adam. Murdered by Cain.',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Seth','Third son of Adam, of the lineage unto Noah.',130,1042,NULL,'father'::public.parent_relationship,NULL),
	 ('Enos','Son of Seth',235,1135,NULL,'father'::public.parent_relationship,NULL),
	 ('Cainan','Son of Enos',325,1235,NULL,'father'::public.parent_relationship,NULL),
	 ('Mahalaleel','Son of Cainan',395,1290,NULL,'father'::public.parent_relationship,NULL),
	 ('Jared','Son of Mahalaleel',460,1422,NULL,'father'::public.parent_relationship,NULL),
	 ('Enoch','Son of Jared. Walked with God 365 years and did not die, for God took him.',622,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Methuselah','Son of Enoch',687,1656,NULL,'father'::public.parent_relationship,NULL),
	 ('Lamech','Son of Methuselah',874,1469,NULL,'father'::public.parent_relationship,NULL),
	 ('Noah','Son of Lamech. Built the ark. Survived flood. Inheritor of earth post flood.',1056,2006,NULL,'father'::public.parent_relationship,NULL),
	 ('Shem','Son of Noah. Of the lineage unto Abraham.',1558,2158,NULL,'father'::public.parent_relationship,NULL),
	 ('Ham','Son of Noah.',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Japheth','Son of Noah',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Gomer','Son of Japeth',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Magog','Son of Japheth',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Madai','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Javan','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Tubal','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Meshech','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Tiras','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Ashkenaz','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Riphath','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Togarmah','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Enoch','Son of Cain',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Irad','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Mehujael','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Methusael','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Lamech','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Adah','Wife of Lamech of Cain',NULL,NULL,NULL,NULL,'wife'::public.spouse_relationship),
	 ('Zillah','Wife of Lamech of Cain',NULL,NULL,NULL,NULL,'wife'::public.spouse_relationship),
	 ('Jabel','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Jubal','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Tubal-cain','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Naahmah','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Elishah','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Tarshish','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Kittim','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Dodanim','',NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Cush',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Mizraim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Canaan',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Phut',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Seba',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Havilah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Sabtah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Raamah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Sabtecha',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Sheba',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Dedan',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Nimrod',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Ludim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Anamim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Lehabim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Naphtuhim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Pathrusim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Casluhim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Caphtorim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Sidon',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Heth',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Elam',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Asshur',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Lud',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Aram',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Uz',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Hul',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Gether',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Mash',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Joktan',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Almodad',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Sheleph',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Hazarmaveth',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Jerah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Hadoram',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Uzal',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Diklah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Obal',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Abimael',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Sheba',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Ophir',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Havilah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Jobab',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Arphaxad',NULL,1658,2096,NULL,'father'::public.parent_relationship,NULL),
	 ('Salah',NULL,1693,2126,NULL,'father'::public.parent_relationship,NULL),
	 ('Eber',NULL,1723,2187,NULL,'father'::public.parent_relationship,NULL),
	 ('Peleg',NULL,1757,1996,NULL,'father'::public.parent_relationship,NULL),
	 ('Reu','',1787,2026,NULL,'father'::public.parent_relationship,NULL),
	 ('Serug','',1819,2049,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Nahor','',1849,1997,NULL,'father'::public.parent_relationship,NULL),
	 ('Nahor',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Haran',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Terah','',1878,2083,NULL,'father'::public.parent_relationship,NULL),
	 ('Abraham','Son of Terah. Father of Isaac and Jacob/Israel. Originally named Abram. God made a promise to make children a multitude and great nation, and that a savior would come of this nation that would save the whole world, namely, Jesus Christ, the Son of God.',1948,2123,'{Abram}','father'::public.parent_relationship,NULL),
	 ('Lot',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Sarah','Wife of Abraham/Abram. Originally named Sarai. Mother of Isaac.',NULL,NULL,'{Sarai}',NULL,'wife'::public.spouse_relationship),
	 ('Milcah','',NULL,NULL,NULL,'father'::public.parent_relationship,'wife'::public.spouse_relationship),
	 ('Iscah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Hagar','Wife of Abram. Mother of Ishmael. Sarai''s maid.',NULL,NULL,NULL,NULL,'wife'::public.spouse_relationship);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Moab',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Ben-ammi',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Isaac','Son of Abraham and Sarah. Father of Jacob and Israel. Husband of Rebekah.',2048,2228,NULL,'father'::public.parent_relationship,NULL),
	 ('Philistim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Huz',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Buz',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Kemuel',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Chesed',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Hazo',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Pildash',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Jidlaph',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Bethuel',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Rebekah','Wife of Isaac. Mother of Esau/Edom and Jacob/Israel.',NULL,NULL,NULL,'father'::public.parent_relationship,'wife'::public.spouse_relationship),
	 ('Reumah','Concubine of Nahor.',NULL,NULL,NULL,NULL,'wife'::public.spouse_relationship),
	 ('Tebah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Gaham',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Thahash',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Maachah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Keturah','Wife of Abraham.',NULL,NULL,NULL,NULL,'wife'::public.spouse_relationship),
	 ('Zimran',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Jokshan',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Medan',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Midian',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Ishbak',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Shuah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Sheba',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Dedan',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Asshurim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Letushim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Leummim',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Ephah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Epher',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Hanoch',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Abida',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Eldaah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Nebajoth',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Kedar',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Adbeel',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Mibsam',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Mishma',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Dumah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Massa',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Hadar',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Tema',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Jetur',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Naphish',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Kedemah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Esau','Son of Isaac. Also called Edom. Brother of Job/Israel.',2108,NULL,'{Edom}','father'::public.parent_relationship,NULL),
	 ('Ishmael',NULL,2034,2171,NULL,'father'::public.parent_relationship,NULL),
	 ('Israel','Son of Isaac. Twin brother of Esau/Edom. Also called Jacob.',2108,2255,'{Jacob}','father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Judith','',NULL,NULL,NULL,NULL,'wife'::public.spouse_relationship),
	 ('Bashemath','',NULL,NULL,NULL,NULL,'wife'::public.spouse_relationship),
	 ('Laban',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Leah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,'husband'::public.spouse_relationship),
	 ('Rachel',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,'husband'::public.spouse_relationship),
	 ('Bilhah','',NULL,NULL,NULL,NULL,'husband'::public.spouse_relationship),
	 ('Zilpah','',NULL,NULL,NULL,NULL,'husband'::public.spouse_relationship),
	 ('Reuben',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Simeon',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Levi',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL);
INSERT INTO public.members ("name",description,birth_year,death_year,alt_names,parent_relationship,spouse_relationship) VALUES
	 ('Judah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Dan',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Naphtali',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Gad',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Asher',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Issachar',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Zebulun',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Dinah',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Benjamin',NULL,NULL,NULL,NULL,'father'::public.parent_relationship,NULL),
	 ('Joseph',NULL,2182,2292,NULL,'father'::public.parent_relationship,NULL);
